Update test_swell.yml

diff --git a/.github/test_swell.yml b/.github/test_swell.yml
--- a/.github/test_swell.yml
+++ b/.github/test_swell.yml
@@ -1,4 +1,4 @@
-name: Swell Tier 1 Applications Tests (Discover)
+name: Swell Tier 2 Applications Tests (Discover)
 
 on: workflow_call
 
@@ -6,10 +6,8 @@ defaults:
   run:
     shell: bash
 
-env:
-  CI_BASE: /discover/nobackup/gmao_ci/swell/tier1
-
 jobs:
+
   # Define the suite list once
   define-matrix:
     runs-on: nccs-discover
@@ -20,36 +18,121 @@ jobs:
       - name: Set suite list
         id: set-suites
         run: |
-          SUITES='["3dvar_cycle", "3dfgat_cycle", "hofx", "3dvar", "3dvar_atmos", "3dfgat_atmos", "localensembleda"]'
+          SUITES='["hofx", "3dfgat_cycle", "3dfgat_atmos"]'
           echo "suites=$SUITES" >> $GITHUB_OUTPUT
-          echo "suites_space=3dvar_cycle 3dfgat_cycle hofx 3dvar 3dvar_atmos 3dfgat_atmos localensembleda" >> $GITHUB_OUTPUT
+          echo "suites_space=hofx 3dfgat_cycle 3dfgat_atmos" >> $GITHUB_OUTPUT
+
+  define-comparison-matrix:
+    runs-on: nccs-discover
+    outputs:
+      comparison_suites: ${{ steps.set-comparison-suites.out }}
+      comparison_suites_space: ${{ steps.set-comparison-suites.outputs.comparison_suites_space }}
+    steps:
+      - name: Set comparison suite list
+        id: set-comparison-suites
+        run: |
+          SUITES='["3dfgat_cycle", "3dfgat_atmos"]'
+          echo "comparison_suites=$SUITES" >> $GITHUB_OUTPUT
+          echo "comparison_suites_space=3dfgat_cycle-comparison 3dfgat_atmos-comparison" >> $GITHUB_OUTPUT
 
   # Initialization needed by all the workflows
-  swell-tier_1-setup:
+  # ------------------------------------------
+  swell-tier_2-setup:
+
     runs-on: nccs-discover
     timeout-minutes: 30
     needs: define-matrix
     steps:
       - name: validate-workflow
-        run: /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} swell
+        run: |
+          /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} swell
+
+      # Only one tier 2 run is allowed at a given time
+      - name: establish-workflow-status
+        run: |
+          if [ -f "/discover/nobackup/gmao_ci/swell/tier2/__running__" ]; then echo "Tier 2 is already running. Abort"; exit 1; fi
+          touch /discover/nobackup/gmao_ci/swell/tier2/__running__
 
       - name: acquire-swell
         uses: actions/checkout@v3
 
       - name: install-swell
         run: |
-          mkdir ${{ env.CI_BASE }}/${GITHUB_RUN_ID}
-          cp ${GITHUB_WORKSPACE}/src/swell/deployment/platforms/nccs_discover_sles15/modules ${{ env.CI_BASE }}/${GITHUB_RUN_ID}/
-          source ${{ env.CI_BASE }}/${GITHUB_RUN_ID}/modules
-          pip install --prefix=${{ env.CI_BASE }}/${GITHUB_RUN_ID}/swell -r ${GITHUB_WORKSPACE}/requirements.txt --no-cache-dir ${GITHUB_WORKSPACE}
+          # Make experiment directory
+          mkdir -p /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}
+          # Copy and source modules
+          cp ${GITHUB_WORKSPACE}/src/swell/deployment/platforms/nccs_discover_sles15/modules /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/
+          source /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/modules
+          pip install --prefix=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/swell -r ${GITHUB_WORKSPACE}/requirements.txt --no-cache-dir ${GITHUB_WORKSPACE}
+          # Remove source code (needed to ensure nothing relies on the source)
 
-  # Run all test workflows using matrix
-  swell-tier_1-test:
+  # --------------------------------------------
+  # STEP1: BUILD JEDI CODE FROM DEVELOP BRANCHES
+  # --------------------------------------------
+
+  swell-tier_2-build_jedi:
+
     runs-on: nccs-discover
     timeout-minutes: 600
-    needs: [define-matrix, swell-tier_1-setup]
+    needs: swell-tier_2-setup
+
+    steps:
+
+      - name: run-swell-build_jedi
+        run: |
+          CI_WORKSPACE=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}
+          SUITE_NAME=build_jedi
+          CI_WORKSPACE_JOB=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/${SUITE_NAME}
+          EXPERIMENT_ID=swell-${SUITE_NAME}-${GITHUB_RUN_ID}
+
+          mkdir -p $CI_WORKSPACE_JOB
+
+          source /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/modules
+
+          # Get python version
+          PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
+
+          export PATH=$CI_WORKSPACE/swell/bin:$PATH
+          export PYTHONPATH=${PYTHONPATH}:$CI_WORKSPACE/swell/lib/python$PYVER/site-packages
+
+          echo "experiment_id: $EXPERIMENT_ID" > $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          echo "experiment_root: $CI_WORKSPACE_JOB" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+
+          rm -r -f $HOME/cylc-run/${EXPERIMENT_ID}-suite
+
+          cd $CI_WORKSPACE_JOB
+          swell create ${SUITE_NAME} -m defaults -p nccs_discover_sles15 -o $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          swell launch $CI_WORKSPACE_JOB/${EXPERIMENT_ID}/${EXPERIMENT_ID}-suite --no-detach --log_path $CI_WORKSPACE_JOB/${EXPERIMENT_ID}
+
+          # Create symbolic link to build that does not involve $GITHUB_RUN_ID
+          ln -s $CI_WORKSPACE_JOB/${EXPERIMENT_ID}/jedi_bundle $CI_WORKSPACE_JOB/jedi_bundle
+
+  # Move experiment directory on failure
+  swell-tier_2-build_jedi-failure:
+
+    runs-on: nccs-discover
+    timeout-minutes: 30
+    needs: swell-tier_2-build_jedi
+    if: failure()
+
+    steps:
+      - name: Fail hold for build_jedi
+        run: |
+          SUITE_NAME=build_jedi
+          CI_WORKSPACE_JOB=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/${SUITE_NAME}
+          mv $CI_WORKSPACE_JOB ${CI_WORKSPACE_JOB}_FAILED
+
+
+  # ----------------------------------------
+  # STEP2: RUN TESTING SUITES WITH NEW BUILD
+  # ----------------------------------------
+  swell-tier_2-test:
+    runs-on: nccs-discover
+    timeout-minutes: 600
+    needs: [define-matrix, swell-tier_2-setup, swell-tier_2-build_jedi]
     strategy:
       fail-fast: false
+      max-parallel: 5
       matrix:
         suite: ${{ fromJson(needs.define-matrix.outputs.suites) }}
 
@@ -59,24 +142,27 @@ jobs:
           CI_WORKSPACE=${{ env.CI_BASE }}/${GITHUB_RUN_ID}
           SUITE_NAME=${{ matrix.suite }}
           CI_WORKSPACE_JOB=${CI_WORKSPACE}/${SUITE_NAME}
-          EXPERIMENT_ID=swell-${SUITE_NAME}-${GITHUB_RUN_ID}
+          EXPERIMENT_ID=swell${SUITE_NAME}-${GITHUB_RUN_ID}
 
           mkdir -p $CI_WORKSPACE_JOB
           source ${CI_WORKSPACE}/modules
 
-          PYVER=$(python --version | awk '{print $2}' | awk -F. '{print $1"."$2}')
+          PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
+
           export PATH=$CI_WORKSPACE/swell/bin:$PATH
           export PYTHONPATH=${PYTHONPATH}:$CI_WORKSPACE/swell/lib/python$PYVER/site-packages
 
           cat > $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml <<EOF
           experiment_id: $EXPERIMENT_ID
           experiment_root: $CI_WORKSPACE_JOB
+          existing_jedi_source_directory: /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/build_jedi/jedi_bundle/source"
+          existing_jedi_build_directory: /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/build_jedi/jedi_bundle/build"
           EOF
 
           rm -rf $HOME/cylc-run/${EXPERIMENT_ID}-suite
 
           cd $CI_WORKSPACE_JOB
-          swell create ${SUITE_NAME} -m defaults -p nccs_discover_sles15 -o $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          swell create ${SUITE_NAME} -m defaults -p nccs_discover_sles15 -o $CI_WORKSPACE_JOB/${SUITE_NAME}
           swell launch $CI_WORKSPACE_JOB/${EXPERIMENT_ID}/${EXPERIMENT_ID}-suite --no-detach --log_path $CI_WORKSPACE_JOB/${EXPERIMENT_ID}
 
       - name: Mark failed on failure
@@ -85,30 +171,119 @@ jobs:
           CI_WORKSPACE_JOB=${{ env.CI_BASE }}/${GITHUB_RUN_ID}/${{ matrix.suite }}
           mv $CI_WORKSPACE_JOB ${CI_WORKSPACE_JOB}_FAILED || true
 
-  # Cleanup on success
-  swell-tier_1-clean_up_success:
+
+  swell-tier2-comparison:
+
     runs-on: nccs-discover
     timeout-minutes: 30
-    needs: [define-matrix, swell-tier_1-test]
-    steps:
-      - name: Remove the run directory
-        run: rm -rf ${{ env.CI_BASE }}/${GITHUB_RUN_ID}
+    needs: [define-comparison-matrix, swell-tier_2-setup, swell-tier_2-test]
+    strategy:
+      fail-fast: false
+      max-parallel: 5
+      matrix:
+        suite: ${{ fromJson(needs.define-comparison-matrix.outputs.comparison_suites) }}
 
-  # Cleanup always (cylc logs and R2D2)
-  swell-tier_1-clean_up_always:
+    steps:
+      - name: run-swell-${{ matrix.suite }}-comparison
+        run: |
+
+          CI_WORKSPACE=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}
+          
+          SUITE_NAME=${{ matrix.suite }}-comparison
+
+          if [ "${{ matrix.suite }}" == "3dfgat_cycle" ]; then
+            CONFIG_NAME=compare_fgat_marine
+          else
+            CONFIG_NAME=compare_variational_atmosphere
+
+          CI_WORKSPACE_JOB=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/${SUITE_NAME}
+          EXPERIMENT_ID=swell-${SUITE_NAME}-${GITHUB_RUN_ID}
+
+          mkdir -p $CI_WORKSPACE_JOB
+
+          source /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/modules
+
+          # Get python version
+          PYVER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
+
+          export PATH=$CI_WORKSPACE/swell/bin:$PATH
+          export PYTHONPATH=${PYTHONPATH}:$CI_WORKSPACE/swell/lib/python$PYVER/site-packages
+
+          echo "experiment_id: $EXPERIMENT_ID" > $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          echo "experiment_root: $CI_WORKSPACE_JOB" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          echo "publish_directory: /discover/nobackup/gmao_ci/swell_publication_location" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+
+          COMPARISON_EXP_PATH_1=/discover/nobackup/gmao_ci/swell/tier2/stable/${SUITE_NAME}/swell-${SUITE_NAME}-*/swell-${SUITE_NAME}-*-suite/experiment.yaml
+
+          EXPERIMENT_ID_2=swell-${COMPARISON_SUITE}-${GITHUB_RUN_ID}
+          COMPARISON_EXP_PATH_2=/discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID}/${COMPARISON_SUITE}/${EXPERIMENT_ID_2}/${EXPERIMENT_ID_2}-suite/experiment.yaml
+
+          echo "comparison_experiment_paths:" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          echo "- $COMPARISON_EXP_PATH_1" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          echo "- $COMPARISON_EXP_PATH_2" >> $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+
+          rm -r -f $HOME/cylc-run/${EXPERIMENT_ID}-suite
+
+          cd $CI_WORKSPACE_JOB
+          swell create ${CONFIG_NAME} -m defaults -p nccs_discover_sles15 -o $CI_WORKSPACE_JOB/${SUITE_NAME}-override.yaml
+          swell launch $CI_WORKSPACE_JOB/${EXPERIMENT_ID}/${EXPERIMENT_ID}-suite --no-detach --log_path $CI_WORKSPACE_JOB/${EXPERIMENT_ID}
+
+  # -------------------------------------------------------------
+  # STEP3: PERFORM UPDATES OF STABLE NIGHTLY POINTER AND CLEAN UP
+  # -------------------------------------------------------------
+
+  # Update the nightly pointer (only runs if tier 1 tests were sucessful)
+  # --------------------------
+  swell-tier_2-update_if_stable:
+
     runs-on: nccs-discover
     timeout-minutes: 30
-    needs: [define-matrix, swell-tier_1-test]
-    if: always()
-    steps:
-      - name: Remove cylc logging directories
-        run: |
-          for suite in ${{ needs.define-matrix.outputs.suites_space }}; do
-            rm -rf $HOME/cylc-run/swell-${suite}-${GITHUB_RUN_ID}-suite
-          done
+    needs: [swell-tier_2-test, swell-tier_2-comparison]
 
-      - name: Remove R2D2 experiment output
+    steps:
+      - name: Replace link to stable with link to current run and remove old directory
         run: |
-          for suite in ${{ needs.define-matrix.outputs.suites_space }}; do
-            rm -rf /discover/nobackup/gmao_ci/R2D2DataStore/Local/ncdiag/ob/swell-${suite}-${GITHUB_RUN_ID}
-          done
+          # Get full path to previous sucessful run
+          previous_stable=`readlink -f /discover/nobackup/gmao_ci/swell/tier2/stable`
+
+          # Remove link
+          rm -f /discover/nobackup/gmao_ci/swell/tier2/stable
+
+          # Link to new stable
+          ln -sf /discover/nobackup/gmao_ci/swell/tier2/${GITHUB_RUN_ID} /discover/nobackup/gmao_ci/swell/tier2/stable
+
+          # Remove old stable
+          echo "Removing previous stable: $previous_stable"
+          rm -r -f $previous_stable
+
+      # Remove the running lock if the update was sucessful
+      - name: Remove the running lock
+        run: |
+          rm -f /discover/nobackup/gmao_ci/swell/tier2/__running__
+
+  # Perform all the clean up (always runs regardless of success of failure)
+  # ------------------------
+
+  swell-tier_2-clean_up:
+
+    runs-on: nccs-discover
+    timeout-minutes: 30
+    needs: [swell-tier_2-test, swell-tier_2-comparison]
+    if: always()  # Always run the clean up, even if failed or cancelled
+
+    steps:
+      - name: Remove the cylc logging directories
+        run: |
+          rm -r -f $HOME/cylc-run/swell-hofx-${GITHUB_RUN_ID}-suite
+          rm -r -f $HOME/cylc-run/swell-3dfgat_cycle-${GITHUB_RUN_ID}-suite
+          rm -r -f $HOME/cylc-run/swell-3dfgat_atmos-${GITHUB_RUN_ID}-suite
+          rm -r -f $HOME/cylc-run/swell-build_jedi-${GITHUB_RUN_ID}-suite
+          rm -r -f $HOME/cylc-run/swell-3dfgat_cycle-comparison-${GITHUB_RUN_ID}-suite
+          rm -r -f $HOME/cylc-run/swell-3dfgat_atmos-comparison-${GITHUB_RUN_ID}-suite
+
+      - name: Remove the R2D2 experiment output
+        run: |
+          rm -r -f /discover/nobackup/gmao_ci/R2D2DataStore/Local/ncdiag/ob/swell-hofx-${GITHUB_RUN_ID}
+          rm -r -f /discover/nobackup/gmao_ci/R2D2DataStore/Local/ncdiag/ob/swell-3dfgat_cycle-${GITHUB_RUN_ID}
+          rm -r -f /discover/nobackup/gmao_ci/R2D2DataStore/Local/ncdiag/ob/swell-3dfgat_atmos-${GITHUB_RUN_ID}
+          rm -r -f /discover/nobackup/gmao_ci/R2D2DataStore/Local/mom6_cice6_UFS
