Experiment scaffolding w/ inputs from parent workflow

diff --git a/.github/workflows/geosongpu-ondemand.yml b/.github/workflows/geosongpu-ondemand.yml
--- a/.github/workflows/geosongpu-ondemand.yml
+++ b/.github/workflows/geosongpu-ondemand.yml
@@ -2,7 +2,16 @@
 
 name: geosongpu-ondemand
 
-on: workflow_call
+on: 
+  workflow_dispatch:
+  workflow_call:
+    inputs:
+      experiment_name:
+        required: true
+        type: string
+      experiment_action:
+        required: true
+        type: string
 
 env:
   CI_ROOT: $NOBACKUP/geosongpu
@@ -23,6 +32,43 @@ jobs:
         run: |
           /home/jardizzo/bin/nams_check.py ${{ github.triggering_actor }} geosongpu
 
-      - name: heartbeat
+      - name: establish-workflow-status
         run: |
-          /discover/nobackup/fgdeconi/work/ci/heartbeat.py
+          if [ -f "$CI_ROOT/.lock" ]; then echo "Lock file present. Aborting."; exit 1; fi
+          mkdir -p $CI_ROOT
+          touch $CI_ROOT/.lock
+
+      - name: set-environment
+        run: |
+          echo "CI_DATETIME=$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV
+          echo "CI_WORKSPACE=$CI_ROOT/$CI_DATETIME" >> $GITHUB_ENV
+
+      - name: create-CI-workspace
+        run: |
+          mkdir -p $CI_WORKSPACE
+          cd $CI_ROOT
+          /bin/rm -f active
+          ln -s $CI_DATETIME active
+          
+      - name: acquire-geosongpu-ci
+        uses: actions/checkout@v3
+        with:
+          repository: GEOS-ESM/geosongpu-ci
+          path: geosongpu-ci
+
+      - name: experiment-run
+        run: |
+          pip install --prefix=$CI_WORKSPACE/geosongpu-ci $GITHUB_WORKSPACE/geosongpu-ci
+          cd $CI_WORKSPACE/geosongpu-ci
+          python3 -m geosongpu-ci.dispatch  ${{ inputs.experiment_name }}  ${{ inputs.experiment_version }}
+  
+      - name: cleanup
+        run: |
+          cd $CI_WORKSPACE
+          /bin/rm *
+
+      - name: exit-workflow
+        run: |
+          /bin/rm -f $CI_ROOT/.lock
+          echo "Workflow complete"
+  
