Add back running flag

diff --git a/.github/workflows/swell-tier2_application_discover.yml b/.github/workflows/swell-tier2_application_discover.yml
--- a/.github/workflows/swell-tier2_application_discover.yml
+++ b/.github/workflows/swell-tier2_application_discover.yml
@@ -57,8 +57,8 @@ jobs:
       # Only one tier 2 run is allowed at a given time
       - name: establish-workflow-status
         run: |
-          #if [ -f "/discover/nobackup/gmao_ci/swell/tier2/__running__" ]; then echo "Tier 2 is already running. Abort"; exit 1; fi
-          #touch /discover/nobackup/gmao_ci/swell/tier2/__running__
+          if [ -f "/discover/nobackup/gmao_ci/swell/tier2/__running__" ]; then echo "Tier 2 is already running. Abort"; exit 1; fi
+            touch /discover/nobackup/gmao_ci/swell/tier2/__running__
           echo "hi"
 
       - name: acquire-swell
